---
name: packer-wireguard-04

on:
  push:
    branches:
      - master
    paths:
      - 'examples/04-aws-wireguard-vpn/packer/**'
  pull_request:
    branches:
      - master
    paths:
      - 'examples/04-aws-wireguard-vpn/packer/**'
  workflow_dispatch:

concurrency:
  group: packer-wireguard-04-${{ github.ref }}
  cancel-in-progress: false

jobs:
  validate:
    if: github.event_name == 'pull_request'
    runs-on: ubuntu-latest
    name: Validate Packer

    permissions:
      id-token: write
      contents: read

    steps:
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@8df5847569e6427dd6c4fb1cf565c83acfa8afa7 # v6
        with:
          role-to-assume: ${{ secrets.OIDC_ROLE_ARN }}
          role-session-name: GithubActionsPackerValidate
          aws-region: eu-west-1

      - name: Setup Packer
        uses: hashicorp/setup-packer@1aa358be5cf73883762b302a3a03abd66e75b232 # v3

      - name: Packer Init
        working-directory: examples/04-aws-wireguard-vpn/packer
        run: packer init wireguard.pkr.hcl

      - name: Packer Validate
        working-directory: examples/04-aws-wireguard-vpn/packer
        run: packer validate -var-file=wireguard-prod.pkvars.hcl wireguard.pkr.hcl

  build:
    if: github.event_name == 'push' || github.event_name == 'workflow_dispatch'
    uses: ./.github/workflows/packer-build.yaml
    with:
      name: wireguard-04
      packer_directory: examples/04-aws-wireguard-vpn/packer
      pkvars_file: wireguard-prod.pkvars.hcl
      pkr_file: wireguard.pkr.hcl
      aws_region: eu-west-1
    secrets:
      OIDC_ROLE_ARN: ${{ secrets.OIDC_ROLE_ARN }}
